name: Validate JSON Schemas

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  validate-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        # Required to mount the Github Workspace to a volume
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_LAKSHANA_USERNAME }}
          password: ${{ secrets.DOCKER_LAKSHANA_PASSWORD }}
          registry: docker.io
          image: la002/jsonschema_validator:v1
          run: |
            ls -a
            docker run -v $(pwd)/schemas:/schemas la002/jsonschema_validator:v1 validate_jsonschema /schemas/*.json